platform :ios, '7.0'
pod 'EasyIOS', :git=>'https://github.com/zhuchaowe/EasyIOS.git'
pod 'EasyIOS-Extention', '~> 1.2'
pod 'UIColor+MLPFlatColors', '~> 1.0'
pod 'UMengAnalytics', '~> 3.1.2'
pod 'TOWebViewController', '~> 2.0.13'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'HTHorizontalSelectionList', '~> 0.3.1'