platform :ios, '7.0'
pod 'EasyIOS', '~> 2.2'
pod 'EasyIOS-Extention', '~> 1.1'
pod 'UIColor+MLPFlatColors', '~> 1.0'
pod 'UMengAnalytics', '~> 3.1.2'
pod 'TOWebViewController', '~> 2.0.13'
pod 'SWTableViewCell', '~> 0.3.7'